//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LouMapInfoApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LouMapInfoApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap building_barracks_menu {
            get {
                object obj = ResourceManager.GetObject("building_barracks_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_casern_menu {
            get {
                object obj = ResourceManager.GetObject("building_casern_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_cityguard_house_menu {
            get {
                object obj = ResourceManager.GetObject("building_cityguard_house_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_cottage_menu {
            get {
                object obj = ResourceManager.GetObject("building_cottage_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_farm {
            get {
                object obj = ResourceManager.GetObject("building_farm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_farm_new_menu {
            get {
                object obj = ResourceManager.GetObject("building_farm_new_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_harbour_menu {
            get {
                object obj = ResourceManager.GetObject("building_harbour_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_hideout_menu {
            get {
                object obj = ResourceManager.GetObject("building_hideout_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_hut {
            get {
                object obj = ResourceManager.GetObject("building_hut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_hut_new_menu {
            get {
                object obj = ResourceManager.GetObject("building_hut_new_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_iron_furnace_menu {
            get {
                object obj = ResourceManager.GetObject("building_iron_furnace_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_lumber_mill_menu {
            get {
                object obj = ResourceManager.GetObject("building_lumber_mill_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_mage_tower_menu {
            get {
                object obj = ResourceManager.GetObject("building_mage_tower_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_market_place_menu {
            get {
                object obj = ResourceManager.GetObject("building_market_place_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_mill_menu {
            get {
                object obj = ResourceManager.GetObject("building_mill_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_mine {
            get {
                object obj = ResourceManager.GetObject("building_mine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_ore_mine_new_menu {
            get {
                object obj = ResourceManager.GetObject("building_ore_mine_new_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_quarry_new_menu {
            get {
                object obj = ResourceManager.GetObject("building_quarry_new_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_shipyard_menu {
            get {
                object obj = ResourceManager.GetObject("building_shipyard_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_stables_menu {
            get {
                object obj = ResourceManager.GetObject("building_stables_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_stone_quarry {
            get {
                object obj = ResourceManager.GetObject("building_stone_quarry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_stonecutter_menu {
            get {
                object obj = ResourceManager.GetObject("building_stonecutter_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_storage_menu {
            get {
                object obj = ResourceManager.GetObject("building_storage_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_stronghold_menu {
            get {
                object obj = ResourceManager.GetObject("building_stronghold_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_temple_menu {
            get {
                object obj = ResourceManager.GetObject("building_temple_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_townhouse_menu {
            get {
                object obj = ResourceManager.GetObject("building_townhouse_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_weapon_factory_menu {
            get {
                object obj = ResourceManager.GetObject("building_weapon_factory_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clipboard_icon {
            get {
                object obj = ResourceManager.GetObject("clipboard_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap corn_1x1_01 {
            get {
                object obj = ResourceManager.GetObject("corn_1x1_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap forrest_big_01 {
            get {
                object obj = ResourceManager.GetObject("forrest_big_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_build_slots {
            get {
                object obj = ResourceManager.GetObject("icon_build_slots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_gold {
            get {
                object obj = ResourceManager.GetObject("icon_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_recruit_slots {
            get {
                object obj = ResourceManager.GetObject("icon_recruit_slots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon icone_LOU {
            get {
                object obj = ResourceManager.GetObject("icone_LOU", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap internet_browser_icon {
            get {
                object obj = ResourceManager.GetObject("internet_browser_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iron_r_1x1_01 {
            get {
                object obj = ResourceManager.GetObject("iron_r_1x1_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lake_m_1x1_01 {
            get {
                object obj = ResourceManager.GetObject("lake_m_1x1_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_LOU {
            get {
                object obj = ResourceManager.GetObject("logo_LOU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LordOfUltima {
            get {
                object obj = ResourceManager.GetObject("LordOfUltima", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_Empire {
            get {
                object obj = ResourceManager.GetObject("menu_Empire", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_Map {
            get {
                object obj = ResourceManager.GetObject("menu_Map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_Official {
            get {
                object obj = ResourceManager.GetObject("menu_Official", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_Tools {
            get {
                object obj = ResourceManager.GetObject("menu_Tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_Zeus {
            get {
                object obj = ResourceManager.GetObject("menu_Zeus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Office_excel_csv_icon {
            get {
                object obj = ResourceManager.GetObject("Office_excel_csv_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_barracks {
            get {
                object obj = ResourceManager.GetObject("pl_building_barracks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_casern {
            get {
                object obj = ResourceManager.GetObject("pl_building_casern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_cityguard_house {
            get {
                object obj = ResourceManager.GetObject("pl_building_cityguard_house", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_cottage {
            get {
                object obj = ResourceManager.GetObject("pl_building_cottage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_farm {
            get {
                object obj = ResourceManager.GetObject("pl_building_farm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_farm_old {
            get {
                object obj = ResourceManager.GetObject("pl_building_farm_old", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_harbour {
            get {
                object obj = ResourceManager.GetObject("pl_building_harbour", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_hideout {
            get {
                object obj = ResourceManager.GetObject("pl_building_hideout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_hut {
            get {
                object obj = ResourceManager.GetObject("pl_building_hut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_hut_old {
            get {
                object obj = ResourceManager.GetObject("pl_building_hut_old", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_iron_furnace {
            get {
                object obj = ResourceManager.GetObject("pl_building_iron_furnace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_lumber_mill {
            get {
                object obj = ResourceManager.GetObject("pl_building_lumber_mill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_mage_tower {
            get {
                object obj = ResourceManager.GetObject("pl_building_mage_tower", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_market_place {
            get {
                object obj = ResourceManager.GetObject("pl_building_market_place", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_mill {
            get {
                object obj = ResourceManager.GetObject("pl_building_mill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_mine {
            get {
                object obj = ResourceManager.GetObject("pl_building_mine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_mine_old {
            get {
                object obj = ResourceManager.GetObject("pl_building_mine_old", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_shipyard {
            get {
                object obj = ResourceManager.GetObject("pl_building_shipyard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_stables {
            get {
                object obj = ResourceManager.GetObject("pl_building_stables", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_stone_quarry {
            get {
                object obj = ResourceManager.GetObject("pl_building_stone_quarry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_stone_quarry_old {
            get {
                object obj = ResourceManager.GetObject("pl_building_stone_quarry_old", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_stonecutter {
            get {
                object obj = ResourceManager.GetObject("pl_building_stonecutter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_storage {
            get {
                object obj = ResourceManager.GetObject("pl_building_storage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_stronghold {
            get {
                object obj = ResourceManager.GetObject("pl_building_stronghold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_temple {
            get {
                object obj = ResourceManager.GetObject("pl_building_temple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_townhall {
            get {
                object obj = ResourceManager.GetObject("pl_building_townhall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_townhouse {
            get {
                object obj = ResourceManager.GetObject("pl_building_townhouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_building_weapon_factory {
            get {
                object obj = ResourceManager.GetObject("pl_building_weapon_factory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_decal_select_building {
            get {
                object obj = ResourceManager.GetObject("pl_decal_select_building", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_res_farmland {
            get {
                object obj = ResourceManager.GetObject("pl_res_farmland", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_res_forest {
            get {
                object obj = ResourceManager.GetObject("pl_res_forest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_res_iron {
            get {
                object obj = ResourceManager.GetObject("pl_res_iron", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_res_lake {
            get {
                object obj = ResourceManager.GetObject("pl_res_lake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_res_stone {
            get {
                object obj = ResourceManager.GetObject("pl_res_stone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_town_bg {
            get {
                object obj = ResourceManager.GetObject("pl_town_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pl_town_bg_water {
            get {
                object obj = ResourceManager.GetObject("pl_town_bg_water", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap popup_icon {
            get {
                object obj = ResourceManager.GetObject("popup_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh_icon {
            get {
                object obj = ResourceManager.GetObject("Refresh_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap res_food {
            get {
                object obj = ResourceManager.GetObject("res_food", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap res_iron {
            get {
                object obj = ResourceManager.GetObject("res_iron", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap res_stone {
            get {
                object obj = ResourceManager.GetObject("res_stone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap res_wood {
            get {
                object obj = ResourceManager.GetObject("res_wood", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stone_m_1x1_01 {
            get {
                object obj = ResourceManager.GetObject("stone_m_1x1_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trade_cart {
            get {
                object obj = ResourceManager.GetObject("trade_cart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trade_ship {
            get {
                object obj = ResourceManager.GetObject("trade_ship", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
